package com.revlog.assets

import java.io.File
import java.nio.file.{Files, Path}
import java.nio.charset.StandardCharsets
import scala.io.Source
import scala.annotation.tailrec

import com.revlog.utils.{LogManager, LogLevel, ConfigManager}
import com.revlog.Main


case class Template(val templateName: String, val templateFields: Map[String, FieldType], val templateContent: String) {

    @tailrec
    final def generateMarkdown(fields: Map[String, String], result: String = templateContent): String = {
        if (fields.isEmpty) {
            Template.comment + "\n\n\n" + result  
        }
        else {
            val head = fields.head

            val newResult = templateFields.get(head._1) match {
                case Some(value) => result.replace("$" + s"${head._1}:${value.toString.toLowerCase}", head._2)
                
                case None => result
            }

            generateMarkdown(fields.tail, newResult)
        }
    }
}

object Template {
    protected final val comment = 
        """|<!--
        |   Generated by revlog.
        |   Do not edit this file directly.
        |-->""".stripMargin
    
    val default = Template(
        "default",
        Map(
            ("title" -> FieldType.Text),
            ("ratingStars" -> FieldType.Computed),
            ("rating" -> FieldType.Float),
            ("firstImpression" -> FieldType.Text),
            ("reviewContent" -> FieldType.Text)
        ),
        """
           |<p align="center">
           |  <font size="6"><b>𓆩 『$title:text』 𓆪</b></font><br><br>
           |  <font size="4">$ratingStars:computed</font><br><br>
           |  <font size="4"><b>$rating:float</b></font>
           |</p>
           |
           |---
           |
           |<p align="center">
           |  <font size="5"><b>── Ⅰ. 余韻 ──</b></font>
           |</p>
           |
           |> $firstImpression:text
           |
           |---
           |
           |<p align="center">
           |  <font size="5"><b>── Ⅱ. 感想ノート ──</b></font>
           |</p>
           |
           |$reviewContent:text
           |
           |---
           |
           |<p align="center">
           |  <font size="4">◇─────── 記録された感想 ───────◇</font>
           |</p>
        """.stripMargin
    )

    val importantFields = Map(
        ("title" -> FieldType.Text),
        ("rating" -> FieldType.Float),
        ("creationDate" -> FieldType.Computed),
        ("modifyDate" -> FieldType.Computed)
    )

    def writeMarkdown(md: String, reviewName: String): Unit = {
        try {
            Files.write(Path.of(Main.reviewsDirectory, reviewName + ".md"), md.getBytes(StandardCharsets.UTF_8))
        } catch {
            case e: Exception => LogManager.log("Was unable to write to markdown to file!", LogLevel.Warning)
        }
    }

    def repairTemplateFields(fields: Map[String, FieldType]): Map[String, FieldType] = fields ++ importantFields

    def verifyFields(fields: Map[String, String]): Boolean = {
        fields.contains("title") 
            && fields.contains("rating")
            && fields.contains("creationDate")
            && fields.contains("modifyDate")
            && fields.contains("usedTemplate")
    }

    def buildFields(fields: Map[String, String]): Map[String, String] = {
        val config = ConfigManager.getConfig()
        fields.flatMap { case (key, value) => 
            key match {
                case "rating" => {
                    val maxRating = ConfigManager.getValueOrDefault(config, "maxRating").toFloat.toInt
                    val fullStar = ConfigManager.getValueOrDefault(config, "fullStar")
                    val halfStar = ConfigManager.getValueOrDefault(config, "halfStar")
                    val emptyStar = ConfigManager.getValueOrDefault(config, "emptyStar")

                    val rating = value.toFloat
                    val ratingInt = rating.toInt
                    val stars: String = if (rating % 1 != 0) {
                        val emptyCount = maxRating - ratingInt - 1

                        s"${fullStar * ratingInt}${halfStar}${emptyStar * emptyCount}"
                    } else {
                        val emptyCount = maxRating - ratingInt

                        s"${fullStar * ratingInt}${emptyStar * emptyCount}"
                    }

                    Map(
                        ("ratingStars" -> s"${stars}"),
                        (key -> s"${rating}/${maxRating}")
                    )
                }
                
                case _ => Map((key -> value))
            }
        }
    }

    def getAllFrom(dirPath: String): List[Template] = {
        val file = new File(dirPath)
        if (file.exists()) {
            val fileList = file.listFiles()
                .filter(f => f.isFile)
                .map(f => f.getPath())
                .filter(f => f.endsWith(".md"))
                .toList

            if (fileList.length < 1) {
                LogManager.log("No templates in template folder.", LogLevel.Log)

                Nil
            } else {
                fromFiles(fileList)
            }
        } else {
            LogManager.log("Template directory doesn't exist!",  LogLevel.Warning)

            Nil
        }
    }

    @tailrec
    private def fromFiles(paths: List[String], result: List[Template] = Nil): List[Template] = {
        paths match {
            case Nil => result.reverse

            case head :: tail => {
                val newResult = fromPath(head) match {
                    case Some(value) => value::result

                    case None => result
                }

                fromFiles(tail, newResult)
            }
        }
    }

    def fromPath(path: String): Option[Template] = {
        val file = new File(path)
        if (file.exists() && file.isFile()) {
            val source = Source.fromFile(file)

            try {
                val content = source.mkString
                val pattern = """\$([a-zA-Z0-9_]+):([a-zA-Z]+)""".r

                val fields = pattern.findAllIn(content).toList

                if (fields.length > 0)  {
                    val fileName = file.getName()
                    val dotPos = fileName.lastIndexOf(".")
                    val templateName = if (dotPos == -1) fileName else fileName.substring(0, dotPos)

                    val template = Template(templateName, getFieldsInfo(fields), content)
                    Some(template)
                } else {
                    LogManager.log(s"No field in '$path'", LogLevel.Warning)

                    None
                }
            } catch {
                case e: Exception => {
                    LogManager.log(s"Unable to read file '$path'!", LogLevel.Warning)

                    None
                }
            } finally {
                source.close()
            }
        } else {
            LogManager.log(s"File '$path' doesn't exists!", LogLevel.Warning)

            None
        }
    }

    @tailrec
    private def getFieldsInfo(fields: List[String], result: Map[String, FieldType] = Map()): Map[String, FieldType] = {
        fields match {
            case Nil => result

            case head :: tail => {
                val semicolonPos = head.lastIndexOf(":")

                val fieldName = head.substring(1, semicolonPos)
                val fieldTypeStr = head.substring(semicolonPos + 1, head.length())

                val fieldType = fieldTypeStr match {
                    case "float" => FieldType.Float
                    case "bool" => FieldType.Boolean
                    case "computed" => FieldType.Computed
                    case _ => FieldType.Text
                }

                getFieldsInfo(tail, result + (fieldName -> fieldType))
            }
        }
    }
}